# my global config
global:
  scrape_interval:     15s 
  evaluation_interval: 2s
  external_labels:
      monitor: 'codelab-monitor'

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
  - job_name: 'snake'
    scrape_interval: 300ms
    scrape_timeout: 300ms
    static_configs:
      - targets: ['battlesnake:9292']

